-- ===============================================================================
-- 1. Female Audience ka dat show kro?
SELECT * FROM Audience WHERE gender='Female';
-- ===============================================================================
-- Sirf Karachi wali audience show kro?
SELECT * FROM Audience WHERE city= 'Karachi';
-- ===============================================================================
-- ROW + Column Filtering;
SELECT age, city FROM Audience WHERE age>= 25 AND city = 'Lahore';

-- Show Audience who are either from karachi OR lahore?
SELECT * FROM Audience WHERE city= 'Karachi' OR city= 'Lahore';
-- ===============================================================================
-- Summer Sale campaign ke ilawa sari campaigns show krwao?
SELECT * FROM Campaigns WHERE campaign_name <> 'Summer Sale';
-- ===============================================================================
-- shows all audience members whose age is greater than 30
SELECT * FROM Audience Where age>30;
-- ===============================================================================
-- show all campaigns whose budget is greater than 50000
SELECT * From Campaigns Where budget>50000;
-- ===============================================================================
-- Show All channels where cost-per_click is less than 1.00
SELECT * From Campaign_Channel Where cost<1.00;
-- ===============================================================================
-- AGGREGATE FUNCTIONS:
-- HOW many customers are in our database?
SELECT COUNT(*) FROM Audience;
-- ===============================================================================
-- How many campaigns are there?
Select COUNT(*) FROM Campaigns;
-- ===============================================================================
-- How many audience members are from karachi?
SELECT COUNT(*) FROM Audience where city = 'Karachi';
-- ===============================================================================
-- SUM FUCTION:
-- show the total revenue generated by all campaigns 
SELECT SUM(budget) FROM Campaigns;
-- ===============================================================================
-- Calculate the total advertising cost spent across all campaign-achannel records;
SELECT SUM(cost) FROM Campaign_Channel;
-- ===============================================================================
-- How much budget did we allocatte only to campaigns whose budget is greater than 50,000;
Select SUM(budget) from Campaigns where budget > 50000;
--  ==============================================================================
select * from Campaigns;
select * from Channels;
select * from Audience;
select * from Campaign_Channel;
select * from Campaign_Performance;
-- ===============================================================================
-- Show the name of each campaign and the total revenue it generated.
Select c.Campaign_Name, SUM(cp.Revenue)
From Campaigns c
inner join Campaign_Performance cp
ON c.campaign_id = cp.campaign_id
Group By Campaign_Name;
-- ===============================================================================
-- Display the campaign names that have a budget greater than the average campaign budget.
Select Campaign_Name 
From Campaigns
where budget>
      (select Avg(budget)
      From Campaigns
);
-- ===============================================================================
-- Show each channel name along with the number of campaigns using that channel.
Select ch.Channel_Name, count(cch.Campaign_id)
From Channels ch
Inner join Campaign_Channel cch
ON ch.channel_id=cch.channel_id
Group By ch.Channel_Name;
-- ===============================================================================
-- Find the campaign that generated the highest revenue.
Select c.Campaign_Name, cp.revenue
From Campaigns c
inner join Campaign_Performance cp
On c.campaign_id = cp.campaign_id
ORDER BY cp.Revenue DESC
LIMIT 1;
-- ===============================================================================
-- Display each campaign name and the total amount spent on its marketing channels.
Select c.Campaign_Name, Sum(ch.cost)
From Campaigns c
Inner join Campaign_Channel ch
ON c.campaign_id=ch.campaign_id
Group By c.Campaign_Name;
-- ===============================================================================
-- Show the average revenue generated by campaigns.
Select AVG(revenue)
From Campaign_Performance;